// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';


function next_tick(cb) {
  setTimeout(cb, 0);
  return /* () */0;
}

export {
  next_tick ,
  
}
/* No side effect */
