// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

import * as Block from "bs-platform/lib/es6/block.js";

function prop(key, value) {
  return /* Prop */Block.__(5, [
            key,
            value
          ]);
}

function attr(key, value) {
  return /* Attr */Block.__(6, [
            key,
            value
          ]);
}

function style(key, value) {
  return /* Style */Block.__(1, [/* tuple */[
              key,
              value
            ]]);
}

export {
  prop  ,
  attr  ,
  style ,
  
}
/* No side effect */
