// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

import * as Snabbdom_base from "./snabbdom_base.js";

function div(param) {
  return Snabbdom_base.h("div", param);
}

function h1(param) {
  return Snabbdom_base.h("h1", param);
}

function p(param) {
  return Snabbdom_base.h("p", param);
}

function input(param) {
  return Snabbdom_base.h("input", param);
}

function label(param) {
  return Snabbdom_base.h("label", param);
}

function span(param) {
  return Snabbdom_base.h("span", param);
}

function button(param) {
  return Snabbdom_base.h("button", param);
}

var h = Snabbdom_base.h;

export {
  h      ,
  div    ,
  h1     ,
  p      ,
  input  ,
  label  ,
  span   ,
  button ,
  
}
/* Snabbdom_base Not a pure module */
