// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';



    var bs_snabbdom = {
        empty_data: function() { return {}; },
        set_in_path: function(data, path, value){
            var base = data || {};
            var ref = base;
            while(path.length > 1){
                var next = path.shift();
                ref[next] = ref[next] || {};
                ref = ref[next];
            }
            if(path.length == 1) {
                var next = path.shift();
                ref[next] = value;
            }
            return base;
        }
    };
    
;

function empty() {
  return bs_snabbdom.empty_data();
}

function set_in_path(data, path, value) {
  return bs_snabbdom.set_in_path(data, path, value);
}

var Data = /* module */[
  /* empty */empty,
  /* set_in_path */set_in_path
];

var VNode = /* module */[];

var Dom = /* module */[];

export {
  Data  ,
  VNode ,
  Dom   ,
  
}
/*  Not a pure module */
