// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

var raw_empty = (function() { return {} } );

var raw_set_in_path = (
function(data, path, value){
    var base = data || {};
    var ref = base;
    while(path.length > 1){
        var next = path.shift();
        ref[next] = ref[next] || {};
        ref = ref[next];
    }
    if(path.length == 1) {
        var next = path.shift();
        ref[next] = value;
    }
    return base;
}
);

function empty() {
  return Curry._1(raw_empty, /* () */0);
}

var set_in_path = Curry.__3(raw_set_in_path);

export {
  empty ,
  set_in_path ,
  
}
/* raw_empty Not a pure module */
