// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Js_primitive    from "bs-platform/lib/es6/js_primitive.js";
import * as Snabbdom_dom    from "./snabbdom_dom.js";
import * as Snabbdom_data   from "./snabbdom_data.js";
import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

function empty() {
  return {
          sel: undefined,
          data: Snabbdom_data.empty(/* () */0),
          children: undefined,
          elm: undefined,
          text: undefined,
          key: undefined
        };
}

function clear_text(vnode) {
  vnode.children = undefined;
  return /* () */0;
}

function set_in_data(path, value, vnode) {
  vnode.data = Snabbdom_data.set_in_path(vnode.data, path, value);
  return vnode;
}

var Element_with_id_not_found = Caml_exceptions.create("Snabbdom_vnode.Element_with_id_not_found");

function from_dom_id(dom_id) {
  var match = Snabbdom_dom.get_element_by_id(Snabbdom_dom.$$document, dom_id);
  if (match) {
    return match[0];
  } else {
    throw [
          Element_with_id_not_found,
          dom_id
        ];
  }
}

function set_sel(prim, prim$1) {
  prim.sel = prim$1;
  return /* () */0;
}

function set_data(prim, prim$1) {
  prim.data = prim$1;
  return /* () */0;
}

function set_children(prim, prim$1) {
  prim.children = prim$1;
  return /* () */0;
}

function set_text(prim, prim$1) {
  prim.text = prim$1;
  return /* () */0;
}

function set_key(prim, prim$1) {
  prim.key = prim$1;
  return /* () */0;
}

function get_children(prim) {
  return Js_primitive.null_undefined_to_opt(prim.children);
}

function get_elm(prim) {
  return Js_primitive.null_undefined_to_opt(prim.elm);
}

function get_text(prim) {
  return Js_primitive.null_undefined_to_opt(prim.text);
}

function of_dom_element(prim) {
  return prim;
}

export {
  empty                     ,
  set_sel                   ,
  set_data                  ,
  set_children              ,
  set_text                  ,
  set_key                   ,
  clear_text                ,
  get_children              ,
  get_elm                   ,
  get_text                  ,
  set_in_data               ,
  Element_with_id_not_found ,
  from_dom_id               ,
  of_dom_element            ,
  
}
/* Snabbdom_dom Not a pure module */
