// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Snabbdom_base from "./snabbdom_base.js";

function next_tick(cb) {
  setTimeout(cb, 0);
  return /* () */0;
}

var mouse = Snabbdom_base.set_event_listener;

var $$event = Snabbdom_base.set_event_listener;

function change(param) {
  return Snabbdom_base.set_event_listener("change", param);
}

function click(param) {
  return Snabbdom_base.set_event_listener("click", param);
}

function mousedown(param) {
  return Snabbdom_base.set_event_listener("mousedown", param);
}

function mouseup(param) {
  return Snabbdom_base.set_event_listener("mouseup", param);
}

function mousemove(param) {
  return Snabbdom_base.set_event_listener("mousemove", param);
}

var keyboard = Snabbdom_base.set_event_listener;

function keydown(param) {
  return Snabbdom_base.set_event_listener("keydown", param);
}

function keyup(param) {
  return Snabbdom_base.set_event_listener("keyup", param);
}

function keypress(param) {
  return Snabbdom_base.set_event_listener("keypress", param);
}

var drag = Snabbdom_base.set_event_listener;

function dragenter(param) {
  return Snabbdom_base.set_event_listener("dragenter", param);
}

function dragover(param) {
  return Snabbdom_base.set_event_listener("dragover", param);
}

function dragleave(param) {
  return Snabbdom_base.set_event_listener("dragleave", param);
}

function drop(param) {
  return Snabbdom_base.set_event_listener("drop", param);
}

export {
  next_tick ,
  mouse     ,
  $$event   ,
  change    ,
  click     ,
  mousedown ,
  mouseup   ,
  mousemove ,
  keyboard  ,
  keydown   ,
  keyup     ,
  keypress  ,
  drag      ,
  dragenter ,
  dragover  ,
  dragleave ,
  drop      ,
  
}
/* Snabbdom_base Not a pure module */
