// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

function focus(prim) {
  prim.focus();
  return /* () */0;
}

var $$document = document;

function get_element_by_id(prim, prim$1) {
  return Js_primitive.null_to_opt(prim.getElementById(prim$1));
}

function stop_propagation(prim) {
  prim.stopPropagation();
  return /* () */0;
}

function prevent_default(prim) {
  prim.preventDefault();
  return /* () */0;
}

function get_target(prim) {
  return prim.target;
}

function get_value(prim) {
  return prim.value;
}

function get_event_key(prim) {
  return prim.key;
}

function is_checked(prim) {
  return +prim.checked;
}

function set_timeout(prim, prim$1) {
  return setTimeout(prim, prim$1);
}

export {
  focus             ,
  $$document        ,
  get_element_by_id ,
  stop_propagation  ,
  prevent_default   ,
  get_target        ,
  get_value         ,
  get_event_key     ,
  is_checked        ,
  set_timeout       ,
  
}
/* document Not a pure module */
