// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Snabbdom_base     from "./snabbdom_base.js";
import * as Snabbdom_external from "./snabbdom_external.js";

function next_tick(cb) {
  Snabbdom_external.Dom[/* set_timeout */8](cb, 0);
  return /* () */0;
}

function event_listener(key, cb) {
  var partial_arg = /* array */[
    "on",
    key
  ];
  return (function (param) {
      return Snabbdom_base.set_data_path(partial_arg, cb, param);
    });
}

var $$event = event_listener;

function change(param) {
  return event_listener("change", param);
}

var mouse = event_listener;

function click(param) {
  return event_listener("click", param);
}

function mousedown(param) {
  return event_listener("mousedown", param);
}

function mouseup(param) {
  return event_listener("mouseup", param);
}

function mousemove(param) {
  return event_listener("mousemove", param);
}

var keyboard = event_listener;

function keydown(param) {
  return event_listener("keydown", param);
}

function keyup(param) {
  return event_listener("keyup", param);
}

function keypress(param) {
  return event_listener("keypress", param);
}

var drag = event_listener;

function dragenter(param) {
  return event_listener("dragenter", param);
}

function dragover(param) {
  return event_listener("dragover", param);
}

function dragleave(param) {
  return event_listener("dragleave", param);
}

function drop(param) {
  return event_listener("drop", param);
}

var Ex = 0;

export {
  Ex             ,
  next_tick      ,
  event_listener ,
  $$event        ,
  change         ,
  mouse          ,
  click          ,
  mousedown      ,
  mouseup        ,
  mousemove      ,
  keyboard       ,
  keydown        ,
  keyup          ,
  keypress       ,
  drag           ,
  dragenter      ,
  dragover       ,
  dragleave      ,
  drop           ,
  
}
/* Snabbdom_base Not a pure module */
