// Generated by BUCKLESCRIPT VERSION 1.7.5, PLEASE EDIT WITH CARE
'use strict';

import * as List  from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";

function get_state(store) {
  return store[/* state */0];
}

function reduce_and_update_store(store, action) {
  var new_state = Curry._2(store[/* reducer */2], store[/* state */0], action);
  store[/* state */0] = new_state;
  return List.iter((function (cb) {
                return Curry._1(cb, store);
              }), store[/* on_change */1]);
}

function dispatch(store, action) {
  var match = store[/* dispatcher */3];
  if (match) {
    return Curry._3(match[0], store, (function (param) {
                  return reduce_and_update_store(store, param);
                }), action);
  } else {
    return reduce_and_update_store(store, action);
  }
}

function on_change(store, callback) {
  store[/* on_change */1] = List.append(store[/* on_change */1], /* :: */[
        callback,
        /* [] */0
      ]);
  return /* () */0;
}

function create_store(initial_state, reducer) {
  return /* record */[
          /* state */initial_state,
          /* on_change : [] */0,
          /* reducer */reducer,
          /* dispatcher : None */0
        ];
}

function create_store_with_middleware(initial_state, reducer, middleware) {
  return /* record */[
          /* state */initial_state,
          /* on_change : [] */0,
          /* reducer */reducer,
          /* dispatcher : Some */[middleware]
        ];
}

export {
  get_state                    ,
  reduce_and_update_store      ,
  dispatch                     ,
  on_change                    ,
  create_store                 ,
  create_store_with_middleware ,
  
}
/* No side effect */
