// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as Snabbdom_dom from "./snabbdom_dom.js";
import * as Snabbdom_vnode from "./snabbdom_vnode.js";

function hook(key, cb) {
  var partial_arg = /* array */[
    "hook",
    key
  ];
  return (function (param) {
      return Snabbdom_vnode.set_in_data(partial_arg, cb, param);
    });
}

var hook0 = hook;

var hook1 = hook;

var hook2 = hook;

function pre(cb) {
  return hook("pre", cb);
}

function init(cb) {
  return hook("init", cb);
}

function create(cb) {
  return hook("create", cb);
}

function insert(cb) {
  return hook("insert", cb);
}

function prepatch(cb) {
  return hook("prepatch", cb);
}

function update(cb) {
  return hook("update", cb);
}

function postpatch(cb) {
  return hook("postpatch", cb);
}

function destroy(cb) {
  return hook("destroy", cb);
}

function remove(cb) {
  return hook("remove", cb);
}

function post(cb) {
  return hook("post", cb);
}

var autofocus = hook("insert", (function (vnode) {
        var match = Snabbdom_vnode.get_elm(vnode);
        if (match !== undefined) {
          return Snabbdom_dom.focus(Js_primitive.valFromOption(match));
        } else {
          return /* () */0;
        }
      }));

var VNode = 0;

export {
  VNode ,
  hook ,
  hook0 ,
  hook1 ,
  hook2 ,
  pre ,
  init ,
  create ,
  insert ,
  prepatch ,
  update ,
  postpatch ,
  destroy ,
  remove ,
  post ,
  autofocus ,
  
}
/* autofocus Not a pure module */
