// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

import * as Snabbdom_base from "./snabbdom_base.js";

function hook(key, cb) {
  var partial_arg = /* array */[
    "hook",
    key
  ];
  return (function (param) {
      return Snabbdom_base.set_data_path(partial_arg, cb, param);
    });
}

var hook0 = hook;

var hook1 = hook;

var hook2 = hook;

function insert(cb) {
  return hook("insert", cb);
}

var autofocus = hook("insert", (function (n) {
        n.elm.focus();
        return /* () */0;
      }));

export {
  hook      ,
  hook0     ,
  hook1     ,
  hook2     ,
  insert    ,
  autofocus ,
  
}
/* autofocus Not a pure module */
