// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Snabbdom_dom   = require("./snabbdom_dom.js");
var Snabbdom_vnode = require("./snabbdom_vnode.js");

function hook(key, cb) {
  var partial_arg = /* array */[
    "hook",
    key
  ];
  return (function (param) {
      return Snabbdom_vnode.set_in_data(partial_arg, cb, param);
    });
}

var hook0 = hook;

var hook1 = hook;

var hook2 = hook;

function insert(cb) {
  return hook("insert", cb);
}

var autofocus = hook("insert", (function (vnode) {
        var match = Snabbdom_vnode.get_elm(vnode);
        if (match) {
          return Snabbdom_dom.focus(match[0]);
        } else {
          return /* () */0;
        }
      }));

var VNode = 0;

exports.VNode     = VNode;
exports.hook      = hook;
exports.hook0     = hook0;
exports.hook1     = hook1;
exports.hook2     = hook2;
exports.insert    = insert;
exports.autofocus = autofocus;
/* autofocus Not a pure module */
