// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Snabbdom_vnode = require("./snabbdom_vnode.js");

function prop(key, value) {
  var partial_arg = /* array */[
    "props",
    key
  ];
  return (function (param) {
      return Snabbdom_vnode.set_in_data(partial_arg, value, param);
    });
}

exports.prop = prop;
/* Snabbdom_vnode Not a pure module */
