// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Snabbdom     = require("snabbdom");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");


    var bs_snabbdom = {
        empty_data: function() { return {}; },
        set_in_path: function(data, path, value){
            var base = data || {};
            var ref = base;
            while(path.length > 1){
                var next = path.shift();
                ref[next] = ref[next] || {};
                ref = ref[next];
            }
            if(path.length == 1) {
                var next = path.shift();
                ref[next] = value;
            }
            return base;
        }
    };
    
;

function empty() {
  return bs_snabbdom.empty_data();
}

function set_in_path(data, path, value) {
  return bs_snabbdom.set_in_path(data, path, value);
}

var Data = /* module */[
  /* empty */empty,
  /* set_in_path */set_in_path
];

function empty$1() {
  return {
          sel: undefined,
          data: undefined,
          children: undefined,
          elm: undefined,
          text: undefined,
          key: undefined
        };
}

function clear_text(vnode) {
  vnode.children = undefined;
  return /* () */0;
}

function set_in_path$1(data, path, value) {
  return bs_snabbdom.set_in_path(data, path, value);
}

function VNode_001(prim, prim$1) {
  prim.sel = prim$1;
  return /* () */0;
}

function VNode_002(prim, prim$1) {
  prim.data = prim$1;
  return /* () */0;
}

function VNode_003(prim, prim$1) {
  prim.children = prim$1;
  return /* () */0;
}

function VNode_004(prim, prim$1) {
  prim.text = prim$1;
  return /* () */0;
}

function VNode_005(prim, prim$1) {
  prim.key = prim$1;
  return /* () */0;
}

function VNode_007(prim) {
  return Js_primitive.null_undefined_to_opt(prim.children);
}

function VNode_008(prim) {
  return Js_primitive.null_undefined_to_opt(prim.elm);
}

function VNode_009(prim) {
  return Js_primitive.null_undefined_to_opt(prim.text);
}

function VNode_011(prim) {
  return prim;
}

var VNode = [
  empty$1,
  VNode_001,
  VNode_002,
  VNode_003,
  VNode_004,
  VNode_005,
  clear_text,
  VNode_007,
  VNode_008,
  VNode_009,
  set_in_path$1,
  VNode_011
];

function init(prim) {
  return Snabbdom.init(prim);
}

function Dom_000(prim) {
  prim.focus();
  return /* () */0;
}

function Dom_002(prim, prim$1) {
  return Js_primitive.null_to_opt(prim.getElementById(prim$1));
}

function Dom_003(prim) {
  prim.stopPropagation();
  return /* () */0;
}

function Dom_004(prim) {
  prim.preventDefault();
  return /* () */0;
}

function Dom_005(prim) {
  return prim.target;
}

function Dom_006(prim) {
  return prim.value;
}

function Dom_007(prim) {
  return prim.key;
}

function Dom_008(prim) {
  return +prim.checked;
}

function Dom_009(prim, prim$1) {
  return setTimeout(prim, prim$1);
}

var Dom = [
  Dom_000,
  document,
  Dom_002,
  Dom_003,
  Dom_004,
  Dom_005,
  Dom_006,
  Dom_007,
  Dom_008,
  Dom_009
];

exports.Data  = Data;
exports.VNode = VNode;
exports.init  = init;
exports.Dom   = Dom;
/*  Not a pure module */
