// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function get_state(store) {
  return store[/* state */0];
}

function reduce_and_update_store(store, action) {
  var new_state = Curry._2(store[/* reducer */2], store[/* state */0], action);
  store[/* state */0] = new_state;
  return List.iter((function (cb) {
                return Curry._1(cb, store);
              }), store[/* on_change */1]);
}

function dispatch(store, action) {
  var match = store[/* dispatcher */3];
  if (match !== undefined) {
    return Curry._3(match, store, (function (param) {
                  return reduce_and_update_store(store, param);
                }), action);
  } else {
    return reduce_and_update_store(store, action);
  }
}

function on_change(store, callback) {
  store[/* on_change */1] = List.append(store[/* on_change */1], /* :: */[
        callback,
        /* [] */0
      ]);
  return /* () */0;
}

function create_store(initial_state, reducer) {
  return /* record */[
          /* state */initial_state,
          /* on_change : [] */0,
          /* reducer */reducer,
          /* dispatcher */undefined
        ];
}

function create_store_with_middleware(initial_state, reducer, middleware) {
  return /* record */[
          /* state */initial_state,
          /* on_change : [] */0,
          /* reducer */reducer,
          /* dispatcher */middleware
        ];
}

exports.get_state = get_state;
exports.reduce_and_update_store = reduce_and_update_store;
exports.dispatch = dispatch;
exports.on_change = on_change;
exports.create_store = create_store;
exports.create_store_with_middleware = create_store_with_middleware;
/* No side effect */
