// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function focus(prim) {
  prim.focus();
  return /* () */0;
}

var $$document = document;

function get_element_by_id(prim, prim$1) {
  return Js_primitive.null_to_opt(prim.getElementById(prim$1));
}

function stop_propagation(prim) {
  prim.stopPropagation();
  return /* () */0;
}

function prevent_default(prim) {
  prim.preventDefault();
  return /* () */0;
}

function get_target(prim) {
  return prim.target;
}

function get_value(prim) {
  return prim.value;
}

function get_event_key(prim) {
  return prim.key;
}

function is_checked(prim) {
  return +prim.checked;
}

function set_timeout(prim, prim$1) {
  return setTimeout(prim, prim$1);
}

exports.focus             = focus;
exports.$$document        = $$document;
exports.get_element_by_id = get_element_by_id;
exports.stop_propagation  = stop_propagation;
exports.prevent_default   = prevent_default;
exports.get_target        = get_target;
exports.get_value         = get_value;
exports.get_event_key     = get_event_key;
exports.is_checked        = is_checked;
exports.set_timeout       = set_timeout;
/* document Not a pure module */
