// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Snabbdom_base     = require("./snabbdom_base.js");
var Snabbdom_external = require("./snabbdom_external.js");

function hook(key, cb) {
  var partial_arg = /* array */[
    "hook",
    key
  ];
  return (function (param) {
      return Snabbdom_base.set_data_path(partial_arg, cb, param);
    });
}

var hook0 = hook;

var hook1 = hook;

var hook2 = hook;

function insert(cb) {
  return hook("insert", cb);
}

var autofocus = hook("insert", (function (vnode) {
        var match = Snabbdom_external.VNode[/* get_elm */8](vnode);
        if (match) {
          return Snabbdom_external.Dom[/* focus */0](match[0]);
        } else {
          return /* () */0;
        }
      }));

var Ex = 0;

exports.Ex        = Ex;
exports.hook      = hook;
exports.hook0     = hook0;
exports.hook1     = hook1;
exports.hook2     = hook2;
exports.insert    = insert;
exports.autofocus = autofocus;
/* autofocus Not a pure module */
